image: guix
packages:
  - make
sources:
  - https://git.sr.ht/~abcdw/guile-ares-rs
tasks:
  - check: |
      cd guile-ares-rs
      make check
  - readme: |
      cd guile-ares-rs
      if [[ "$BUILD_SUBMITTER" == "git.sr.ht" ]] then
        make deploy-README.html
      fi
oauth: git.sr.ht/REPOSITORIES:RW git.sr.ht/PROFILE:RO
triggers:
  - action: email
    condition: failure
    to: ~abcdw/rde-devel@lists.sr.ht
