;; SPDX-License-Identifier: GPL-3.0-or-later
;; SPDX-FileCopyrightText: 2023-2026 Andrew Tropin <andrew@trop.in>

(define-module (bencode-test)
  #:use-module (bencode)
  #:use-module (ares suitbl checks)
  #:use-module (ares suitbl definitions))





(define-suite (encode)
  (test ("integers" _)
    (is (equal? "i0e" (scm->bencode-string 0)) "0")
    (is (equal? "i42e" (scm->bencode-string 42)) "42")
    (is (equal? "i-42e" (scm->bencode-string -42)) "-42"))

  (test ("strings" _)
    (is (equal? "4:spam" (scm->bencode-string "spam")) "\"spam\"")
    (is (equal? "6:naïve" (scm->bencode-string "naïve")) "\"naïve\"")
    (is (equal? "0:" (scm->bencode-string "")) "empty string")
    (is (equal? "7:keyword" (scm->bencode-string #:keyword)) "\"keyword\"")
    (is (equal? "6:symbol" (scm->bencode-string 'symbol)) "\"symbol\""))

  (test ("lists" _)
    (is (equal? "le" (scm->bencode-string #())) "empty list")
    (is (equal? "l4:spami-42ee" (scm->bencode-string #("spam" -42)))
        "list with number and string")
    (is (equal? "ll4:spamelei-42ee"
                (scm->bencode-string #(#("spam") #() -42)))
        "list with nested list, number and string")
    (is (equal? "l1:a1:be" (scm->bencode-string #(#:a #:b)))
        "list with keywords")
    (is (equal? "l1:a1:be" (scm->bencode-string #(a b)))
        "list with symbols"))

  (test ("dictionaries" _)
    (is (equal? "de" (scm->bencode-string '())) "empty dict")
    (is (equal? "d4:spami-42ee" (scm->bencode-string '(("spam" . -42))))
        "dict with number and string")
    (is (throws-exception? (scm->bencode-string '((42 . -42)))
                           bencode-encoding-exception?)
        "dict with non-string key")
    (is (equal? "d4:listde4:spami-42ee"
                (scm->bencode-string '(("list")
                                       ("spam" . -42))))
        "dict without value")
    (is (throws-exception? (scm->bencode-string '(("spam") ()))
                           bencode-encoding-exception?)
        "malformed dict with empty key")
    (is (throws-exception? (scm->bencode-string '(("spam") -42))
                           bencode-encoding-exception?)
        "malformed dict with number")
    (is (equal? "d1:ai1ee" (scm->bencode-string '((#:a . 1))))
        "dict with keyword keys")
    (is (equal? "d1:ai1ee" (scm->bencode-string '((a . 1))))
        "dict with symbol keys"))

  (test ("unsupported types" _)
    (is (throws-exception? (scm->bencode-string #f)
                           bencode-encoding-exception?)
        "top-level #f")
    (is (throws-exception? (scm->bencode-string #(#f))
                           bencode-encoding-exception?)
        "#f in list")
    (is (throws-exception? (scm->bencode-string '((#f . "x")))
                           bencode-encoding-exception?)
        "#f as dictionary key")
    (is (throws-exception? (scm->bencode-string '(("x" . #f)))
                           bencode-encoding-exception?)
        "#f as dictionary value")))

(define-suite (decode)
  (test ("integers" _)
    (is (equal? 0 (bencode-string->scm "i0e")) "i0e :: zero")
    (is (throws-exception? (bencode-string->scm "i0a"))
        "i0a :: unexpected character")
    (is (equal? 42 (bencode-string->scm "i42e")) "i42e :: positive number")
    (is (equal? -42 (bencode-string->scm "i-42e"))
        "i-42e :: negative number")
    (is (throws-exception? (bencode-string->scm "i4-2e"))
        "i4-2e :: unexpected character")
    (is (throws-exception? (bencode-string->scm "i--4e"))
        "i--4e :: unexpected character")
    (is (throws-exception? (bencode-string->scm "ie"))
        "ie :: no digits")
    (is (throws-exception? (bencode-string->scm "i-e"))
        "i-e :: no digits")
    (is (throws-exception? (bencode-string->scm "i"))
        "i :: unexpcted EOF")
    (is (throws-exception? (bencode-string->scm "i-12"))
        "i-12 :: unexpcted EOF"))

  (test ("strings" _)
    (is (equal? "" (bencode-string->scm "0:")) "0: :: empty string")
    (is (equal? "spam" (bencode-string->scm "4:spam"))
        "4:spam :: simple string")
    (is (equal? "naïve" (bencode-string->scm "6:naïve")) "6:naïve")
    (is (equal? "sp" (bencode-string->scm "2:sp2:am"))
        "2:sp2:am :: two strings")
    (is (throws-exception? (bencode-string->scm "4:spa"))
        "4:spa :: unexpected EOF"))

  (test ("lists" _)
    (is (equal? #() (bencode-string->scm "le")) "le :: empty list")
    (is (equal? #("spam" 34) (bencode-string->scm "l4:spami34ee"))
        "l4:spami34ee :: simple list with string and integer")
    (is (equal? #(#() #("hi" #() 34))
                (bencode-string->scm "llel2:hilei34eee"))
        "lllel2:hilei34eeee :: nested lists")
    (is (throws-exception? (bencode-string->scm "l"))
        "l :: unexpected EOF"))

  (test ("dictionaries" _)
    (is (equal? '() (bencode-string->scm "de")) "de :: empty string")
    (is (equal? `(("spam" . 34) ("hi" . #("ho")))
                (bencode-string->scm "d4:spami34e2:hil2:hoee"))
        "d4:spami34e2:hil2:hoee :: simple string something dict")
    (is (equal? '(("hey" . (("ho" . 44))))
                (bencode-string->scm "d3:heyd2:hoi44eee"))
        "lllel2:hilei34eeee :: nested dictionaries")
    (is (throws-exception? (bencode-string->scm "di34e2:hie"))
        "di34e2:hie :: non-string key")
    (is (throws-exception? (bencode-string->scm "d"))
        "d :: unexpected EOF")))
